import Head from 'next/head';
import Image from 'next/image';
import Board from '../components/board';
import styles from '../styles/Home.module.css';

import prisma from '../lib/prisma';

import { useState } from 'react';
import { useRouter } from 'next/router';

export default function Home({}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Highscore</h1>
        <Board />
        <p>Create new board</p>
        <form>
          <input type='text' placeholder='Type spill'></input>
        </form>
      </main>

      <footer className={styles.footer}>
        <p>Av Anne-Marie</p>
      </footer>
    </div>
  );
}

// export const getStaticProps = async () => {
//   const feed = await prisma.ParticipantWhereInput.findMany();
//   return {
//     props: { feed },
//     revalidate: 10,
//   };
// };
